pipeline {
    agent any 
    stages {
        stage('Static Analysis') {
            steps {
                echo 'Run the static analysis to the code' 
            }
        }
        stage('Compile') {
            steps {
                echo 'This is the 3rd time I am performing this experiment' 
            }
        }
        stage('Security Check') {
            steps {
                echo 'First time, I did not have a pc' 
            }
        }
        stage('Run Unit Tests') {
            steps {
                echo 'Second Time I forgot to take screenshots and lost all my data' 
            }
        }
        stage('Run Integration Tests') {
            steps {
                echo 'Third Time is the Charm 🤞' 
            }
        }
        stage('Publish Artifacts') {
            steps {
                echo "Or atleast  hope so :')" 
            }
        }
    }
}
